# Stack Overflow Developer Survey Analysis

This project analyzes the Stack Overflow Developer Survey dataset using Pandas.

## 1. Import Libraries

In [1]:
import pandas as pd

## 2. Load Dataset

In [16]:
df = pd.read_csv(
    "Downloads/results.csv",
    low_memory=False
)

## 3. Explore Dataset

In [3]:
df.shape

(49191, 172)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [5]:
df.isna().sum().sort_values(ascending=False).head(10)

AIAgentObsWrite         48927
SOTagsWant Entry        48761
SOTagsHaveEntry         48733
AIModelsWantEntry       48716
AIAgentOrchWrite        48713
JobSatPoints_15_TEXT    48527
AIAgentKnowWrite        48425
AIModelsHaveEntry       48415
SO_Actions_15_TEXT      48368
AIAgentExtWrite         48332
dtype: int64

## Question 1: How Many People Participated in the Survey?

In [6]:
print("Number of survey participants:", df.shape[0])

Number of survey participants: 49191

## Question 2: How Many People Answered All Questions?

In [7]:
answered_all = df.dropna()

answered_all.shape[0]

0

In [8]:
df.notna().all(axis=1).sum()

np.int64(0)

**Note:** No participant answered every question in the survey. This is expected because many survey questions were optional or only shown to specific groups of respondents.

## Question 3: What are the measures of central tendency for WorkExp?

In [9]:
pd.DataFrame({
    "Measure": ["Mean", "Median", "Mode"],
    "Value": [
        df["WorkExp"].mean(),
        df["WorkExp"].median(),
        df["WorkExp"].mode()[0]
    ]
})

  Measure      Value
0    Mean  13.367403
1  Median  10.000000
2    Mode  10.000000

## Question 4: How Many People Work Remotely?

In [10]:
remote_workers = df[df["RemoteWork"] == "Remote"]

print("Number of remote workers:", remote_workers.shape[0])

Number of remote workers: 10931

## Question 5: What Percentage of Respondents Program in Python?

In [11]:
python_users = df["LanguageHaveWorkedWith"].str.contains(
    "Python",
    na=False
)

python_percentage = (
    python_users.sum() / df.shape[0]
) * 100

print(f"Percentage of Python developers: {python_percentage:.2f}%")

Percentage of Python developers: 37.54%

## Question 6: How Many People Learned Programming Through Online Courses?

In [12]:
online_course_users = df["LearnCode"].str.contains(
    "Online Courses",
    na=False
)

print("People who learned through online courses:",
      online_course_users.sum())

People who learned through online courses: 10973

## Question 7: Average and Median Annual Compensation of Python Developers by Country

In [13]:
salary_by_country = (
    df[df["LanguageHaveWorkedWith"].str.contains("Python", na=False)]
    .groupby("Country")["ConvertedCompYearly"]
    .agg(["mean", "median"])
    .sort_values("mean", ascending=False)
)

salary_by_country.head(20)

                                                             mean    median
Country
Oman                                                390135.000000  390135.0
Andorra                                             226103.500000  226103.5
Viet Nam                                            218837.166667    8254.0
United States of America                            173298.590211  150000.0
Switzerland                                         156456.600000  142592.0
Singapore                                           147515.121951   91391.0
Israel                                              135828.365385  142594.0
Nigeria                                             128773.276596    1808.0
Ireland                                             120523.918919  116015.0
Nomadic                                             120131.571429  139218.0
Australia                                           118091.410423   97514.0
United Kingdom of Great Britain and Northern Ir...  117662.362667   94958.5
Luxembourg                                          116014.714286  109054.0
Denmark                                             115672.425000   98289.0
Lebanon                                             115540.000000   65000.0
Kyrgyzstan                                          106008.500000  106008.5
Norway                                              104690.125000   89439.0
Canada                                              102846.026423   87550.0
Belize                                              102121.000000  102121.0
Uruguay                                             100973.818182   49338.0

## Question 8: Education Levels of the Top 5 Highest-Paid Respondents

In [14]:
top_5_education = (
    df.sort_values("ConvertedCompYearly", ascending=False)
    [["ConvertedCompYearly", "EdLevel"]]
    .head(5)
)

top_5_education

       ConvertedCompYearly                                          EdLevel
34267           50000000.0              Associate degree (A.A., A.S., etc.)
28700           33552715.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
43143           18387548.0              Associate degree (A.A., A.S., etc.)
35353           15430267.0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)
45971           13921760.0  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)

In [15]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

# Conclusion

This notebook demonstrates practical data analysis using Python and Pandas on a real-world developer survey dataset.

Key concepts covered include:

- Data exploration
- Missing value analysis
- Descriptive statistics
- Data filtering
- Aggregation
- Survey data analysis

This project demonstrates fundamental exploratory data analysis (EDA) techniques commonly used by data analysts.